include: package:flutter_lints/flutter.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_build_context_synchronously: false
