name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  go_router: ^13.0.0
  dio: ^5.6.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.0
  fl_chart: ^0.68.0
  csv: ^6.0.0
  equatable: ^2.0.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
