// Generated by sync_lib_tree.py
// file: screens/dashboard/widgets/section_header.dart
import 'package:flutter/material.dart';

/// A simple header widget to display a title for a section.
class SectionHeader extends StatelessWidget {
  final String title;
  const SectionHeader(this.title, {super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
      child: Text(
        title,
        style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700),
      ),
    );
  }
}
